### ISSUE TITLE
Crash on starting

### ISSUE THREAD

**Issue by dnlo** [nguyenvinhlinh/HexSearcher#4]
Running:
./hex_searcher trot

Results in this on my machine:
00:31:17.380 [error] SSL: :hello: ssl_alert.erl:88:Fatal error: internal error
Internet Connection Error: {:tls_alert, 'internal error'}
** (exit) 1
    (hex_searcher) lib/hex_searcher.ex:35: HexSearcher.fetch_xml/1
    (hex_searcher) lib/hex_searcher.ex:7: H
x_searcher.ex:35: HexSearcher.fetch_xml/1
    (hex_searcher) lib/hex_searcher.ex:7: HexSearexSearcher.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2

**Comment by nguyenvinhlinh** [comment]
thank you, I am checking the issue.

**Comment by nguyenvinhlinh** [comment]
very weird, here is how the terminal output:
![screenshot from 2017-06-10 00-07-46](https://user-images.githubusercontent.com/5039272/26986256-e94e42ca-4d70-11e7-8e9c-2ab13ad9ab55.png)
Can you verify that the Internet is still available and the time of local machine is up to date. @dnlo
